workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - foln-rist-furi-creds  # <----
      vars:
        BUNDLE_ID: "com.force.rush.might.app" # <----
        XCODE_SCHEME: "MightyForceRushMit" # <----
        APP_STORE_CONNECT_ISSUER_ID: "9748eec5-9c3f-494e-9f74-3533ca9a2da2" # <----
        cocoapods: default
        APP_STORE_CONNECT_KEY_ID: "CL757XRG7B" # <----
        xcode: latest
        node: latest
        XCODE_WORKSPACE: "MightyForceRushMit.xcworkspace" # <----
        APP_STORE_APP_ID: 6759629907 # <----
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: npm install --force
      - name: Install CocoaPods dependencies
        script: cd ios && pod install
      - name: Set up keychain for code signing
        script: keychain initialize
      - name: Fetch signing files
        script: app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: keychain add-certificates
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/ios
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
      - name: Set up code signing settings in Xcode project
        script: xcode-project use-profiles --warn-only
      - name: Build IPA for distribution
        script: xcode-project build-ipa --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME" --archive-flags="-destination 'generic/platform=iOS'"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - cristianricci65@icloud.com       # <----
        notify:
          success: true
          failure: false
      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: false
      app_store_connect:
        api_key: "$APP_STORE_CONNECT_PRIVATE_KEY"
        key_id: "$APP_STORE_CONNECT_KEY_ID"
        issuer_id: "$APP_STORE_CONNECT_ISSUER_ID"
        submit_to_testflight: true
